### ISSUE TITLE
Upload 8.0.1.0 to SonOff basic

### ISSUE THREAD

**Issue by GittaHuby** [tasmota/images#3]
Just tried to update Tasmota from 7.2.0 to 8.1.0.1 onto one of my SonOff Basic. Got the following error message:
++++++
Sonoff Basic Modul
Sonoff_Test_1
Upload fehlgeschlagen

Upload Buffer Vergleich weicht ab
++++++

Another upload onto one of my H801-Devices worked fine, ok.

Any ideas?

best regards,  Dirk

**Comment by Jason2866** [comment]
Wrong place.

**Comment by GittaHuby** [comment]
ok, sorry. And the 'right' place is where?

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
