### ISSUE TITLE
Unable to upload a new image to update the Arduino instructions page

### ISSUE THREAD

**Issue by skaterdude** [tasmota/images#4]
The image of what the board specs should look like in the docs/Arduino-IDE.md page doesn't match the defaults shown right after installation.  I just installed it, and here's what I get:

![Generic8266Specs](https://user-images.githubusercontent.com/749221/76181977-75a72400-6199-11ea-9711-d97732dd8fc9.png)

Although I certainly could have messed something up (in particular, I could not find "Replace in Arduino IDE folder portable\packages\esp8266\hardware\esp8266\2.6.1 file platform.txt with ..." it seems like most of what's there would be accurate.

I am able to change all but one of the options in the Arduino IDE to those shown in the image in the instructions on this page.  Maybe clarify that the user will have to update them?  It currently says "verify" which implies that you should just look at them and make sure they are set to those values.

I just realized that the image shown there is in German.  I was going to mention that I could not find "Keine" in the options for Debug Level, but translating it, Google says it means "No" so I assume that should be "None" in the English version of the interface.  Maybe have two images there?  One in German and one in English?  The other option values in that image all seem to be English, so it's confusing.

**Comment by ascillato** [comment]
The flash size there is incorrect for Tasmota.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
